#!/usr/bin/env python3
"""Mark words that are probably not real words, for human review.

    python3 scripts/language_flagging.py [language]

Stage 2 of four. This writes cognate = "invalid" as a review flag; the web app's
WordValidation component lists those rows, and you either delete them or clear
the flag. Deleting is what makes reparse.py necessary: transcripts on disk still
carry the deleted word ids, and reparse.py re-resolves them.

An earlier variant of this script gave the model each root's first six wordforms
instead of its translation. That is arguably better evidence and is worth porting
back; it was dropped because it cost one query per word and ran a loose prompt at
temperature 0.7.
"""
import json
import os
import sys
from typing import Dict, List

from dotenv import load_dotenv

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

load_dotenv()

from languages import require_code  # noqa: E402
from llm_client import client  # noqa: E402
from models import MODEL_FAST, MODEL_SMART  # noqa: E402
from supabase_client import supabase  # noqa: E402


def fetch_words(language: str, batch_size: int = 40, offset: int = 0) -> List[Dict]:
    """Words to check, skipping the ones that came from a trusted reference list.

    source = "CREA" marks rows seeded from the CREA frequency corpus, which is
    vetted and does not need an LLM opinion. Nothing writes that value any more:
    it was set by the one-shot importer that seeded the original 50k Spanish
    words, and the current importer tags its rows "WORD_LIST". So this filter now
    excludes historical rows only. It is still correct — do not delete it as dead.
    """
    response = supabase.table("words").select("id, root").eq("language", require_code(language)).neq("source", "CREA").range(offset, offset + batch_size - 1).execute()
    return response.data

def parse_chatgpt_output(output: str, startChar: str, endChar: str) -> str:
    start = output.find(startChar)
    end = output.rfind(endChar)
    
    if start == -1 or end == -1 or start > end:
        raise ValueError("No valid JSON object found in the output")
    
    json_content = output[start:end+1]
    return json_content

def verify_language(words: List[Dict], language: str) -> List[str]:
    word_entries = [
        f"{word['root']} (translation: {word.get('translation', 'NONE')})"
        for word in words
    ]
    system_msg = (
        "You are a meticulous Spanish lexicographer. "
        "Your job is to spot tokens that are NOT valid Spanish words so they can be removed from the database."
    )

    user_msg = f"""
    **Task**

    You are given a list of Spanish words, each with a possible English translation (the translation is generated by an AI and may not always be accurate). Not all words have a translation.

    For each token, consider:
    1. Is the word not recognised by Spanish dictionaries (RAE or widely accepted regional)?
    2. Is it an obvious misspelling or nonsense string?
    3. Does it contain a leading article that should be removed (el, la, los, las, un, una, unos, unas)?
    4. Is it a proper name, brand, acronym, or standard scientific/technical term?
    5. **Does the English translation appear nonsensical, unrelated, or suggest that the word is not Spanish (for example, an Italian word with an English translation unrelated to Spanish)?**

    *Having a reasonable translation is NOT a guarantee that the word is valid, but nonsense translations should make you more suspicious of the word.*

    **Output format (strict)**  
    Return **only** a JSON array containing the problematic tokens *exactly as given*, no explanations, no duplicates, no trailing commas.  
    Example: `["el carborundum","rehue"]`

    **Terms to check**  
    {chr(10).join(word_entries)}
    """
    response = client.chat.completions.create(
        model=MODEL_FAST,
        messages=[
            {"role": "system", "content": system_msg},
            {"role": "user", "content": user_msg}
        ],
        max_tokens=2000,
        temperature=0.3,
    )
    raw_output = response.choices[0].message.content
    print(raw_output)
    json_output = parse_chatgpt_output(raw_output, '[', ']')
    non_language_words = json.loads(json_output)
    return non_language_words


def flag_non_language_words(non_language_words: List[str], all_words: List[Dict]):
    # Update flagged status in the database
    print("flagging " + str(non_language_words))
    word_ids_to_flag = [word['id'] for word in all_words if word['root'] in non_language_words]
    for word_id in word_ids_to_flag:
        supabase.table("words").update({"cognate": "invalid"}).eq("id", word_id).execute()
        #supabase.table("words").update({"flagged": True}).eq("id", word_id).execute()

def main(language: str, offset: int = 0):
    batch_size = 40

    while True:
        try:
            print(f"Fetching words to verify language ({language}, offset: {offset})...")
            words = fetch_words(language, batch_size, offset)

            # Without this the loop ran past the end of the table forever,
            # spending a model call on every empty batch.
            if not words:
                print("No more words to check.")
                break

            print(f"Verifying {len(words)} words in {language}...")
            non_language_words = verify_language(words, language)

            if non_language_words:
                print(f"Flagging non-{language} or misspelled words in the database...")
                flag_non_language_words(non_language_words, words)
            else:
                print(f"No non-{language} or misspelled words found in this batch.")
        except Exception as e:
            print(f"Error filtering non-{language} words: {str(e)}")

        offset += batch_size
        print(offset)

if __name__ == "__main__":
    # Second argument resumes a long run: the batch loop prints the offset it
    # reached, and passing that back picks up from there.
    language_to_check = sys.argv[1] if len(sys.argv) > 1 else "spanish"
    start_offset = int(sys.argv[2]) if len(sys.argv) > 2 else 0
    main(language_to_check, start_offset)