#!/usr/bin/env bash
# Pack the transcript corpus into one gzipped tarball per language.
#
# Memory profile: constant. tar streams file-by-file into gzip's 32 KB window;
# neither ever holds more than a few hundred KB regardless of corpus size.
# Do not replace this with a Python script that builds the archive in a BytesIO.
set -euo pipefail

DATA_DIR="${LANGFIVE_DATA_DIR:-$(cd "$(dirname "$0")/.." && pwd)/data}"
OUT_DIR="$DATA_DIR/archives"
SRC="processed"

mkdir -p "$OUT_DIR"

for lang in de es fr it; do
  if [ ! -d "$DATA_DIR/$SRC/$lang" ]; then
    echo "skip $lang (no $SRC/$lang)"
    continue
  fi
  python3 "$(dirname "$0")/build_corpus_metadata.py" "$DATA_DIR/$SRC/$lang"
  echo "packing $lang ..."
  # -C $DATA_DIR so archive members are 'processed/<lang>/...' and extracting
  # into DATA_DIR restores the tree in place.
  tar --exclude='.DS_Store' \
      -czf "$OUT_DIR/$lang.tar.gz.tmp" \
      -C "$DATA_DIR" "$SRC/$lang"
  mv "$OUT_DIR/$lang.tar.gz.tmp" "$OUT_DIR/$lang.tar.gz"
  echo "  -> $(du -h "$OUT_DIR/$lang.tar.gz" | cut -f1)"
done

echo "writing manifest ..."
{
  echo "# generated by scripts/pack_corpus.sh"
  for f in "$OUT_DIR"/*.tar.gz; do
    [ -e "$f" ] || continue
    printf '%s  %s  %s\n' "$(basename "$f")" "$(stat -c%s "$f" 2>/dev/null || stat -f%z "$f")" "$(shasum -a 256 "$f" 2>/dev/null | cut -d' ' -f1 || sha256sum "$f" | cut -d' ' -f1)"
  done
} > "$OUT_DIR/MANIFEST.txt"

echo "DONE"
